In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [33]:
automobiles_data=pd.read_csv('C:/Users/shubham.chhetri/Desktop/MYPROJECT/Machine learning/Deploying ML Solutions/CarPrice_Assignment.csv')

In [34]:
automobiles_data.head()


car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [35]:
automobiles_data.shape

(205, 26)

In [36]:
automobiles_data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [37]:
automobiles_data.drop(['car_ID', 'symboling', 'CarName'],axis=1,inplace=True)

In [38]:
automobiles_data=pd.get_dummies(automobiles_data)
automobiles_data.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [39]:
automobiles_data.shape

(205, 52)

In [40]:
x=automobiles_data.drop('price',axis=1)
y=automobiles_data['price']

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [42]:
x_train.shape,y_train.shape

((164, 51), (164,))

In [43]:
x_test.shape,y_test.shape

((41, 51), (41,))

In [44]:
model=LinearRegression().fit(x_train,y_train)

In [45]:
Training_score=model.score(x_train,y_train)
Training_score

0.9421443099090017

In [46]:
y_pred=model.predict(x_test)
y_pred

array([ 8466.10073481,  5476.85789394, 15449.76385805, 16931.19180586,
       12675.7682874 ,  8426.86494343,  7249.47761844, 12115.29886535,
       21622.45801795,  5946.01929955,  6383.18532984,  6574.04013053,
       37990.64220349,  8154.18184078, 28209.02116251,  5836.6993016 ,
        6018.40693832,  5343.23912694, 18634.72947445, 19229.58373433,
        7508.16080244, 13105.27174552,  9985.08988262, 16781.37561051,
        6445.91651253, 10631.85168164,  9327.4885209 ,  9696.45130862,
        9564.77463138,  7316.95293654, 13390.89987997,  2649.22134423,
       17505.27629731, 20192.68370672, 11415.98762997, 34178.77279836,
       10098.7097682 , 11133.95797743, 10172.06459066, 12623.18688748,
        6789.22254659])

In [47]:
Testing_score=r2_score(y_test,y_pred)
Testing_score

0.8854943458397648

Serialize using JSON

In [48]:
import json

In [49]:
model.coef_

array([ 5.52041198e+01, -6.12484283e+01,  7.26337654e+02,  1.26618074e+00,
        4.19752599e+00,  1.14476523e+02, -1.72823054e+03, -4.59476860e+03,
       -1.25192096e+03,  1.31239003e+00,  2.76056269e+00, -2.34647230e+02,
        2.39870184e+02,  6.41849022e+03, -6.41849022e+03, -5.33538525e+02,
        5.33538525e+02, -2.20114607e+02,  2.20114607e+02,  2.16874772e+03,
       -3.45015542e+02, -1.20706054e+03,  5.53138776e+01, -6.71985509e+02,
       -5.61383106e+02, -2.61368087e+02,  8.22751193e+02, -3.88243001e+03,
        3.88243001e+03, -5.69488605e+01, -1.04591891e-11, -1.36105096e+03,
        3.25112755e+03,  1.41532531e+03, -5.55666265e+03,  2.30820961e+03,
        5.35442830e+03, -4.69370566e+03, -4.68080000e+03, -1.05787070e+03,
        6.24125142e+03, -3.47151298e+03,  2.30820961e+03,  5.38410976e+02,
        6.05898739e+02, -2.09755038e+03,  6.41849022e+03, -2.97409302e+03,
        2.24712783e+02, -2.55075610e+03, -1.65113226e+02])

In [50]:
model.intercept_

-26566.740826543566

In [51]:
model_param={}

model_param['coef']=list(model.coef_)
model_param['intercept']=model.intercept_.tolist()

In [52]:
json_txt=json.dumps(model_param,indent=4)
json_txt

'{\n    "coef": [\n        55.204119823054235,\n        -61.24842832130652,\n        726.3376544462018,\n        1.2661807411796389,\n        4.197525993082053,\n        114.47652288218057,\n        -1728.2305448415884,\n        -4594.768601056249,\n        -1251.920960006968,\n        1.3123900254040564,\n        2.7605626913600645,\n        -234.6472300514938,\n        239.8701836235473,\n        6418.490222763615,\n        -6418.490222763653,\n        -533.5385251282639,\n        533.538525128255,\n        -220.11460650742362,\n        220.11460650742805,\n        2168.7477176663106,\n        -345.01554191687774,\n        -1207.060544252373,\n        55.313877589054925,\n        -671.9855090861072,\n        -561.3831056757733,\n        -261.3680871938112,\n        822.7511928695696,\n        -3882.43001003906,\n        3882.430010039056,\n        -56.9488604985026,\n        -1.0459189070388675e-11,\n        -1361.0509595017365,\n        3251.1275537113665,\n        1415.325305648561

In [53]:
with open('models/regressor_parm.txt','w') as file:
    file.write(json_txt)

In [54]:
with open('models/regressor_parm.txt','r') as file:
    json_text=json.load(file)

In [55]:
json_model=LinearRegression()

In [56]:
json_model.coef_=np.array(json_text['coef'])
json_model.intercept_=np.array(json_text['intercept'])

In [57]:
y_pred=json_model.predict(x_test)
r2_score(y_test,y_pred)

0.8854943458397648

Serialize using pickle

In [59]:
import pickle

In [60]:
pickle.dump(model,open('models/model.pkl','wb'))

In [61]:
pickle_model=pickle.load(open('models/model.pkl','rb'))

In [62]:
y_pred=pickle_model.predict(x_test)
y_pred

array([ 8466.10073481,  5476.85789394, 15449.76385805, 16931.19180586,
       12675.7682874 ,  8426.86494343,  7249.47761844, 12115.29886535,
       21622.45801795,  5946.01929955,  6383.18532984,  6574.04013053,
       37990.64220349,  8154.18184078, 28209.02116251,  5836.6993016 ,
        6018.40693832,  5343.23912694, 18634.72947445, 19229.58373433,
        7508.16080244, 13105.27174552,  9985.08988262, 16781.37561051,
        6445.91651253, 10631.85168164,  9327.4885209 ,  9696.45130862,
        9564.77463138,  7316.95293654, 13390.89987997,  2649.22134423,
       17505.27629731, 20192.68370672, 11415.98762997, 34178.77279836,
       10098.7097682 , 11133.95797743, 10172.06459066, 12623.18688748,
        6789.22254659])

In [63]:
r2_score(y_test,y_pred)

0.8854943458397648

Serialize using joblib

In [64]:
import joblib

In [65]:
filename='models/model.joblib'

In [66]:
joblib.dump(model,filename)

['models/model.joblib']

In [67]:
joblib_model=joblib.load(filename)

In [68]:
y_pred=joblib_model.predict(x_test)
y_pred

array([ 8466.10073481,  5476.85789394, 15449.76385805, 16931.19180586,
       12675.7682874 ,  8426.86494343,  7249.47761844, 12115.29886535,
       21622.45801795,  5946.01929955,  6383.18532984,  6574.04013053,
       37990.64220349,  8154.18184078, 28209.02116251,  5836.6993016 ,
        6018.40693832,  5343.23912694, 18634.72947445, 19229.58373433,
        7508.16080244, 13105.27174552,  9985.08988262, 16781.37561051,
        6445.91651253, 10631.85168164,  9327.4885209 ,  9696.45130862,
        9564.77463138,  7316.95293654, 13390.89987997,  2649.22134423,
       17505.27629731, 20192.68370672, 11415.98762997, 34178.77279836,
       10098.7097682 , 11133.95797743, 10172.06459066, 12623.18688748,
        6789.22254659])

In [69]:
r2_score(y_test,y_pred)

0.8854943458397648